// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9XCNsWdaVh2sH96PPU3HfEy4qpNllZ-4',
    appId: '1:1061944288565:web:30f01b0c19df26c2a2187c',
    messagingSenderId: '1061944288565',
    projectId: 'cinemanow-77cbc',
    authDomain: 'cinemanow-77cbc.firebaseapp.com',
    storageBucket: 'cinemanow-77cbc.firebasestorage.app',
    measurementId: 'G-HY5VHTKBZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdS2PLvd_FbCCvkE60Wz1YjvRNAkDW_68',
    appId: '1:1061944288565:android:a3a410c7f2954dcaa2187c',
    messagingSenderId: '1061944288565',
    projectId: 'cinemanow-77cbc',
    storageBucket: 'cinemanow-77cbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXI1KDJv9qBNV4fdSfV1rvXy_xn_7SNQ',
    appId: '1:1061944288565:ios:8c8eb5ca559f182fa2187c',
    messagingSenderId: '1061944288565',
    projectId: 'cinemanow-77cbc',
    storageBucket: 'cinemanow-77cbc.firebasestorage.app',
    iosBundleId: 'com.example.cinemanow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyXI1KDJv9qBNV4fdSfV1rvXy_xn_7SNQ',
    appId: '1:1061944288565:ios:8c8eb5ca559f182fa2187c',
    messagingSenderId: '1061944288565',
    projectId: 'cinemanow-77cbc',
    storageBucket: 'cinemanow-77cbc.firebasestorage.app',
    iosBundleId: 'com.example.cinemanow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9XCNsWdaVh2sH96PPU3HfEy4qpNllZ-4',
    appId: '1:1061944288565:web:5f1fc3db67c83613a2187c',
    messagingSenderId: '1061944288565',
    projectId: 'cinemanow-77cbc',
    authDomain: 'cinemanow-77cbc.firebaseapp.com',
    storageBucket: 'cinemanow-77cbc.firebasestorage.app',
    measurementId: 'G-09XQ3J3W4S',
  );
}
